name: vertical_scrollable_tabview
description: A Flutter widget which syncronize a ScrollView and a custom tab view.
version: 0.0.7
repository: https://github.com/wayne900204/vertical_scrollable_tabview
issue_tracker: https://github.com/wayne900204/vertical_scrollable_tabview/issues
homepage: https://github.com/wayne900204/vertical_scrollable_tabview
documentation: https://github.com/wayne900204/vertical_scrollable_tabview/blob/master/README.md

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: "3.0.2"

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1
  # rect_getter: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.vertical_scrollable_tabview
        pluginClass: VerticalScrollableTabviewPlugin
      ios:
        pluginClass: VerticalScrollableTabviewPlugin
      web:
        pluginClass: VerticalScrollableTabviewWeb
        fileName: vertical_scrollable_tabview_web.dart
